# Generated by Django 4.0.2 on 2022-05-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_likes_userlikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLikes',
            new_name='PostLikes',
        ),
    ]
